runtime: php55
api_version: 1
threadsafe: true

handlers:

- url: /autocomplete
  script: autocomplete.php

- url: /index.html
  static_files: index.html
  upload: index.html

- url: /(.*)
  static_files: \1
  upload: (.*)
