runtime: php55
api_version: 1
threadsafe: true

handlers:
- url: /(.+\.php)$
  script: \1

- url: /app/(.+\.php)$
  script: \1

- url: /
  static_files: index.html
  upload: index.html

- url: /(.*)
  static_files: \1
  upload: (.*)