runtime: php55
api_version: 1
threadsafe: true

handlers:

- url: /autocomplete
  script: autocomplete.php

- url: /autocomplete2
  script: autocomplete2.php

- url: /
  static_files: index.html
  upload: index.html

- url: /product
  script: product.php

- url: /test
  script: test.php

- url: /static
  static_dir: static

env_variables:
  # Replace project, instance, database, user and password with the values obtained
  # when configuring your Cloud SQL instance.
  MYSQL_DSN: mysql:unix_socket=/cloudsql/rbse-webserv:us-east4:bp;dbname=bp
  MYSQL_USER: root
  MYSQL_PASSWORD: 'elburro123'