runtime: php55
api_version: 1
threadsafe: true

handlers:

- url: /
  script: autocomplete.php

- url: /index.html
  static_files: index.html
  upload: index.html

- url: /js
  static_dir: js

- url: /jquery
 static_dir: jquery

- url: /img
 static_dir: img

 - url: /css
 static_dir: css

