runtime: php55
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /autocomplete.php
  script: autocomplete.php

- url: /(.*)
  static_files: \1
  upload: (.*)

