runtime: php55
api_version: 1
threadsafe: true

handlers:

- url: /autocomplete
  script: autocomplete.php

- url: /
  static_files: index.html
  upload: index.html

- url: /product
  script: product.php

- url: /test
  script: test.php

- url: /static
  static_dir: static