runtime: php55
api_version: 1
threadsafe: true

handlers:

- url: /
  script: autocomplete.php

- url: /index.html
  static_files: index.html
  upload: index.html

- url: /js/autocomplete.js
  static_files: /js/autocomplete.js
  upload: /js/autocomplete.js